### ISSUE TITLE
PTB Language Model Code

### ISSUE THREAD

**Issue by kris-singh** [idiap/importance-sampling#10]
Could you share the PTB Language model code?

**Comment by angeloskath** [comment]
Hi,

do you mean the weights? The code is in `importance_sampling/models.py`.

Angelos

**Comment by kris-singh** [comment]
That files only defines the model. I meant the code for training with PTB dataset as reported in the paper.

**Comment by angeloskath** [comment]
Ok, `scripts/importance_sampling.py` . Are you having trouble just with PTB? Could you tell me specifically what are you having trouble with?

There are examples in the README specifying how to use the script and an extensive command line help. If you are experiencing issues with the latest Keras use an older version, we are currently working on fixing some issues.

In any case, the more specific you are the faster I can help you.

Cheers,
Angelos
