### ISSUE TITLE
Upstream contribution

### ISSUE THREAD

**Issue by bhack** [idiap/importance-sampling#13]
Hi I've tried to open an upstream issue at https://github.com/tensorflow/tensorflow/issues/17509 now that keras api is officially in tf.keras cause I think that it is an important topic and it need to be exposed to a broad audience as API.

Do you have a plan to contribute an upstream PR to keras or to tf.estimator?

**Comment by angeloskath** [comment]
Hi,

I am definitely interested in having this as a part of Keras or TF. However, I don't know if they will feel like including this. I can support your issue tensorflow/tensorflow#17509 and I could probably devote part of my time to change things to fit their purpose.

Do you think I should make a PR? Do you think I should make an issue to investigate the best way to integrate this? Maybe Keras contrib?

In any way, thanks for the help and I am interested in your thoughts on how I should proceed with this.

Cheers,
Angelos

**Comment by bhack** [comment]
The most interesting thing to push is at api level causd we can plug new solution to this problem in the future other than this. I think you can start commenting on that issue. There is also a dev mailing list

**Comment by bhack** [comment]
The most interesting thing is at api level to support this and other techniques that approach this problem. You can try to comment that issue.
