### ISSUE TITLE
Import error with resnet

### ISSUE THREAD

**Issue by AntoineRichard** [idiap/importance-sampling#15]
Hi,

I am using keras 2.2.4, tensorflow 1.8.0, python 3.5.2 in a virtualenv.

I encountered two issues using your framework when trying the command line examples and the cifar10_resnet example. (I am not using the keras package but the source code directly)

Here are the errors code I get:

`File "/home/gpu_user/antoine/importance-sampling/examples/importance_sampling/pretrained.py", line 8, in <module>
    from keras.applications.resnet50 import WEIGHTS_PATH as RESNET50_WEIGHTS_PATH
ImportError: cannot import name 'WEIGHTS_PATH'`

I am not sure whether it is an issue on my Keras installation or your something related to your code, but I fixed it by modifying the **importance_sampling/pretrained.py**:
I replaced:
```python
from keras.applications.resnet50 import WEIGHTS_PATH as RESNET50_WEIGHTS_PATH
```
With:
```python
import keras.applications.resnet50 as RNET
RESNET50_WEIGHTS_PATH = RNET.resnet50.WEIGHTS_PATH
```

Also had the following issue:
`File "cifar10_resnet.py", line 102, in <module>
    model = wide_resnet(args.depth, args.width)(dset.shape, dset.output_size)
  File "/home/gpu_user/antoine/importance-sampling/examples/importance_sampling/models.py", line 438, in wide_resnet_impl
    x = group1(x)
  File "/home/gpu_user/antoine/importance-sampling/examples/importance_sampling/models.py", line 420, in inner
    for i in range(n):
TypeError: 'float' object cannot be interpreted as an integer`

Fixed it by modifying line 427 of **importance_sampling/models.py** with:
```python
n = int((L-4)/6))
```

it ran fine afterwards

Otherwise I liked reading your paper(Not All Sample Are Created Equal: Deep Learning with Importance Sampling), but I have couple questions/observations:
 + In your paper in equation 6 in the last 2 lines I think some transpose operators are missing.
 + In the same paper I am not sure to understand how the \omega_i parameter is used in the SGD. Especially when using the importance sampling.
 + At some point you mention that you let the network warmup for a bit before starting the importance sampling did you do a grid search to find optimal values ? Can you recommend a number of epoch to let it warm up for ? Or you used the Tth defined in the paper as a condition to trigger the importance sampling ?

Thanks,

Antoine

**Comment by angeloskath** [comment]
Hi Antoine, thanks for finding this!!!

Both problems are bugs because the example code is not run by the tests. I will probably need to find a way to do that without asking from the CI to train a couple of networks each time. I will close the issue when I have made a new release with the fixes.

Regarding the paper:

1. Good catch. Added to the errata list and will be fixed when I upload a new version to arxiv
2. w_i is a weight such that the estimator remains unbiased. See the attached file ([sampling_weights.pdf](https://github.com/idiap/importance-sampling/files/2512308/sampling_weights.pdf)) for details.
3. We use the tau defined in the paper. It is the only way to have a guarantee of improvement over uniform sampling. There can be no heuristic because the point to start importance sampling is related to the networks performance so far.

I hope I covered your questions. The issue will remain open until I fix the bugs.

Thanks again for your help!
Cheers,
Angelos

**Comment by AntoineRichard** [comment]
I have one more question if you don't mind !

+ Have you implemented the gradient upper-bound in the framework yet ? I cannot find it: In the paper it is described as marginally more difficult than the value of the loss, however when I look at your code the only thing that I see is the gradient norm, and  that it is computed using gradient values, even in fast mode.

(I'd like to use that directly into tensorflow and I need to rewrite that chunk of code)

Thanks for the help,
Best,
Antoine

**Comment by angeloskath** [comment]
Hi, sorry for the late reply.

Yes of course it is implemented! The experiments of the paper are run using this very code. 

So, the upper bound mentioned in the paper is the one in equation 20. That is still a norm of a gradient but the gradient can be computed in batch mode (see fast) and it only requires backpropagating through the loss and one activation layer which are both element wise and very fast.

The specific pieces of code that compute that upper bound are the following:

- [GradientNormLayer](https://github.com/idiap/importance-sampling/blob/master/importance_sampling/layers/scores.py)
- [_get_scoring_layer()](https://github.com/idiap/importance-sampling/blob/master/importance_sampling/model_wrappers.py)

If you want to see the heuristics for automatically choosing a layer you can see them at the method `OracleWrapper._gnorm_layer()` in the same file as the `_get_scoring_layer()` function.

If you want to write it from scratch in a less general way you could just take the gradients with the pre-activation output of your last layer and then take their norm. That is you upper bound.

Let me know if you have problems implementing it. I might be able to help.

Cheers,
Angelos

**Comment by angeloskath** [comment]
So, I did make a new release. I have fixed those errors and added them to the tests. We still might need to make a test for all the examples but I decided not to deal with it yet.

Thanks for reporting the bug, I am closing the issue but feel free to reopen it (or a new one).

Cheers,
Angelos
