### ISSUE TITLE
Multiple inputs with Functional API error

### ISSUE THREAD

**Issue by lampts** [idiap/importance-sampling#2]
I got this error when running the models with multiple inputs and Model() api in Keras 2.0.6

/lib/python2.7/site-packages/importance_sampling/training.pyc in __init__(self, model, k, smooth, adaptive_smoothing, presample, forward_batch_size)
    263 
    264         # Call the parent to wrap the model
--> 265         super(ImportanceTraining, self).__init__(model)
    266 
    267         # Create the sampler factory, the workhorse of the whole deal :-)

/lib/python2.7/site-packages/importance_sampling/training.pyc in __init__(self, model)
     26         # and can be used in an importance sampling training scheme
     27         self.original_model = model
---> 28         self.model = OracleWrapper(model, self.reweighting)
     29 
     30     @property

/lib/python2.7/site-packages/importance_sampling/model_wrappers.pyc in __init__(self, model, reweighting, score)
    144 
    145     def __init__(self, model, reweighting, score="loss"):
--> 146         self.model = self._augment_model(model, score, reweighting)
    147         self.reweighting = reweighting
    148 

/lib/python2.7/site-packages/importance_sampling/model_wrappers.pyc in _augment_model(self, model, score, reweighting)
    192             inputs=[model.input, y_true, pred_score],
    193             outputs=[weighted_loss],
--> 194             observed_tensors=[loss_tensor, weighted_loss, score_tensor] + metrics
    195         )
    196         new_model.compile(

/lib/python2.7/site-packages/transparent_keras/transparent_model.pyc in __init__(self, inputs, outputs, observed_tensors, **kwargs)
     23             inputs=inputs,
     24             outputs=outputs,
---> 25             **kwargs
     26         )
     27 
/keras/engine/topology.pyc in __init__(self, inputs, outputs, name)
   1498 
   1499         # Check for redundancy in inputs.
-> 1500         if len(set(self.inputs)) != len(self.inputs):
   1501             raise ValueError('The list of inputs passed to the model '
   1502                              'is redundant. '

TypeError: unhashable type: 'list'

How to solve it?

**Comment by angeloskath** [comment]
There is no fundamental reason for it but the current implementation supports **single input - single output models** only. I understand that this is kind of a big limitation so I will make this issue kind of a priority.

**Comment by ryanallen82** [comment]
I'm having the same issue, just so you know it's not a one-off request.

**Comment by Keegil** [comment]
Same here – would greatly appreciate support for models with multiple inputs and outputs!

**Comment by hardikmeisheri** [comment]
Also custom loss functions seem to be unsupported.

**Comment by dminh** [comment]
I have the same need for multiple inputs and outputs too.

**Comment by angeloskath** [comment]
The library now supports **multiple inputs**. Multiple outputs are not so straightforward to implement so you will have to wait a bit more for it :).

Check it out and reply to the issue if you encounter any problems.

@hardikmeisheri Do you mind opening another issue with an example? Because the following code works fine.

```python
from keras import backend as K
from keras.layers import Dense
from keras.models import Sequential
from importance_sampling import ImportanceTraining
import numpy as np

def mse(a, b):
    return K.mean((a-b)**2, axis=1)

model = Sequential([Dense(10, activation="relu", input_dim=2), Dense(10)])
model.compile(loss=mse, optimizer="adam")
ImportanceTraining(model).fit(
    np.random.rand(128, 2),
    np.random.rand(128, 10),
    epochs=2
)
```

**Comment by hardikmeisheri** [comment]
@angeloskath in model.compile instead of 'mse' if I define a custom loss function, it doesn't work.

**Comment by angeloskath** [comment]
@hardikmeisheri  I have not set it to "mse" but rather to `mse` the function defined just above. Still if you have some code example that doesn't work please open another issue so that we are not spamming this one.

**Comment by hardikmeisheri** [comment]
@angeloskath I am getting nan while training. Need to check. Thanks. Sorry for the confusion.

**Comment by angeloskath** [comment]
Guys, I am closing the issue and re-opening one for *multiple outputs*. If anyone experiences problems with *multiple inputs*, open another issue and refer to this one.
