### ISSUE TITLE
How do I get the serial Numbers of important samples

### ISSUE THREAD

**Issue by Garand0o0** [idiap/importance-sampling#27]
hi,
I read the examples/mnist_cnn.The algorithm judges whether the current sample is important or not and justify using important sampling or not.How do I get the serial Numbers of important samples.Where should I add "print()".
thanks.

**Comment by angeloskath** [comment]
Hi,

You can use the `on_sample` callback. You can read more in the [docs](https://www.idiap.ch/~katharas/importance-sampling/training/#sampling-probabilites-and-sample-weights).

Cheers,
Angelos
