### ISSUE TITLE
High GPU memory usage

### ISSUE THREAD

**Issue by MasterScrat** [idiap/importance-sampling#28]
Hello,

Is it normal that training with `ImportanceTraining` takes more GPU memory than training without it? if yes, how much of an overhead should be expected?

I am trying to finetune EfficientNetB3 on an RTX 2070 (8GB), and while it normally works fine (up to a batch size of ~60), it is unusable when using importance sampling (even with batch size of 1). Am I doing anything wrong?

It does work fine when training on CPU, and EfficientNetB0 does work on GPU with IS, which leads me to believe it is not a bug in my code...

**Comment by MasterScrat** [comment]
To clarify, the problem occurs even if IS is not enabled (ie if the threshold condition is not met). It seems that simply wrapping the model with `ImportanceTraining()` makes the GPU memory usage of EfficientNet jump through the roof.

**Comment by angeloskath** [comment]
I cannot reproduce this issue. For instance the following works fine:

```python
from importance_sampling import ImportanceTraining
import efficientnet.keras as efn
import numpy as np

# dummy dataset
x = np.random.rand(1000, 300, 300, 3)
y = np.random.rand(1000, 1000)
y /= y.sum(axis=1, keepdims=True)

model = efn.EfficientNetB3(weights='imagenet')
model.compile(loss="categorical_crossentropy", optimizer="sgd")
model.fit(x, y, batch_size=10)

wrapped = ImportanceTraining(model)
wrapped.fit(x, y, batch_size=10)
```

In addition, both models fail with OOM with a batch size of 32 in a GTX 1080 Ti. Could you please provide a small example to reproduce your issue?

**Comment by MasterScrat** [comment]
Thanks for taking the time, great to hear that this is an issue somewhere on my side and not a limitation of this method. I'll try to reproduce my problem starting from your working example to see what caused it.

Regarding the batch size, this is probably just because my images are smaller (165x95).

**Comment by angeloskath** [comment]
Feel free to reopen if you are still experiencing the problem.
