### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by MasterScrat** [idiap/importance-sampling#29]
I am running multiple `ImportanceSampling` trainings in a row to compare the performance using different models. It looks like the memory is not free'd after the training of each model is over (main memory, not video memory). 

Here is how it looks after training 4 models (on a system with 100gb of RAM):

<img width="764" alt="Screenshot 2020-03-12 at 10 16 16" src="https://user-images.githubusercontent.com/140592/76506085-e0cb5180-644a-11ea-82c4-a21e82194d69.png">

If I don't use `ImportanceSampling`, the memory usage remains stable, and I can train hundreds of successive models in a row.

**Comment by angeloskath** [comment]
I am trying to reproduce this behaviour but I am failing. Could you perhaps create a simple script that exhibits a similar memory leak?

**Comment by angeloskath** [comment]
I am closing the issue due to inactivity. Feel free to reopen.
