### ISSUE TITLE
Question regarding Eq. 29

### ISSUE THREAD

**Issue by liaocs2008** [idiap/importance-sampling#30]
Hi,

May I ask how do you get the square out of the expectation in Eq. 29 in your appendix?

I have this naïve computation plug in "gi" and I get:

sum gi * (wi)^2 * ||Gi||^2 = sum ||Gi||/(B^2)

Could you tell me how to calculate your expectation? Thanks!

**Comment by angeloskath** [comment]
Hi,

So it goes as follows:

```
g_i proportional to |G_i| = |G_i| / sum_j |G_j|
w_i = 1/(B g_i)

E_g[w_i^2 |G_i|^2 ] = sum_i g_i w_i^2 |G_i|^2
                    = 1/B^2 sum_i |G_i|^2 / g_i
                    = 1/B^2 sum_i |G_i|^2 / (|G_i| / sum_j |G_j|)
                    = 1/B^2 (sum_i |G_i|)(sum_j |G_j|)
                    = (sum_i |G_i| / B)^2
```

Cheers,
Angelos
