### ISSUE TITLE
ModuleNotFoundError: No module named 'training'

### ISSUE THREAD

**Issue by jcomfort4** [idiap/importance-sampling#4]
@angeloskath   I am trying to use the importance sampling and am getting the following error:

> \AppData\Local\Continuum\Anaconda3\envs\tensorflow-gpu\lib\site-packages\importance_sampling\__init__.py

 

> in<module>()
     14 __version__ = "0.2"
     15 
---> 16 from training import ImportanceTraining, ApproximateImportanceTraining

> ModuleNotFoundError: No module named 'training'

I installed in my conda environment using "pip install keras-importance-sampling" and almost all requirements were already met except it had to also install blinker and transparent-keras.

Any idea what might be going wrong? I am using Windows, so not sure if that is a compatibility issue?

**Comment by jcomfort4** [comment]
Further - you can see that training.py is in the same conda environment folder so it seems like everything was installed correctly. Is it something with the way windows environments interact with packages that is causing the training module not to be found?

`Directory of C:\Users\username\AppData\Local\Continuum\Anaconda3\envs\tensorflow-gpu\Lib\site-packages\importance_sampling

08/07/2017  06:13 PM    <DIR>          .
08/07/2017  06:13 PM    <DIR>          ..
08/07/2017  06:13 PM            17,899 datasets.py
08/07/2017  06:13 PM            11,446 models.py
08/07/2017  06:13 PM             7,252 model_wrappers.py
08/07/2017  06:13 PM             6,493 reweighting.py
08/07/2017  06:13 PM            16,888 samplers.py
08/07/2017  06:13 PM             3,064 score_layers.py
08/07/2017  06:13 PM            13,708 training.py
08/07/2017  06:13 PM    <DIR>          utils
08/07/2017  06:13 PM               574 __init__.py
08/07/2017  06:13 PM    <DIR>          __pycache__
               8 File(s)         77,324 bytes
               4 Dir(s)  48,816,779,264 bytes free`

**Comment by angeloskath** [comment]
Hi,

Apparently this error is due to my lack of knowledge w.r.t. python 3. I had some intra-package imports that were not relative. I am fixing it and re-releasing. Hopefully everything will be smooth then. I will close the issue after the release.

Thanks a lot for the issue. If you encounter further issues with using python 3 let me know and I will be fixing them as soon as I can.

Angelos
