### ISSUE TITLE
ImportError: No module named 'transparent_model'

### ISSUE THREAD

**Issue by qinhui99** [idiap/importance-sampling#6]
I used "pip install   keras-importance-sampling" to install it in python 3.5 .  My   environment is : 
keras 2.08
win10 64,
Anaconda2
python 3.5

When I tried to run the example named mnist_mlp.py, then I got the errors "No module named 'transparent_model'".  Then I tried to pip install transparent_model, and it did not work.  Did I miss something ?

**Comment by angeloskath** [comment]
It was a bug in the module transparent-keras that only presented on python 3. I just pushed new versions and it is now fixed.

I am sorry for the inconvenience, I will start using continuous integration so that we don't have these regressions again.
