### ISSUE TITLE
All layer names must be unique

### ISSUE THREAD

**Issue by theblackcat102** [idiap/importance-sampling#7]
Hi I tried using importance sampling to keras pretrained Xception models, and this error happens. Is this normal?
`
RuntimeError: ('The name "input_1" is used 2 times in the model. All layer names should be unique. Layer names: ', ['input_1', 'block1_conv1', 'block1_conv1_bn', 'block1_conv1_act', 'block1_conv2', 'block1_conv2_bn', 'block1_conv2_act', 'block2_sepconv1', 'block2_sepconv1_bn', 'block2_sepconv2_act', 'block2_sepconv2', 'block2_sepconv2_bn', 'conv2d_1', 'block2_pool', 'batch_normalization_1', 'add_1', 'block3_sepconv1_act', 'block3_sepconv1', 'block3_sepconv1_bn', 'block3_sepconv2_act', 'block3_sepconv2', 'block3_sepconv2_bn', 'conv2d_2', 'block3_pool', 'batch_normalization_2', 'add_2', 'block4_sepconv1_act', 'block4_sepconv1', 'block4_sepconv1_bn', 'block4_sepconv2_act', 'block4_sepconv2', 'block4_sepconv2_bn', 'conv2d_3', 'block4_pool', 'batch_normalization_3', 'add_3', 'block5_sepconv1_act', 'block5_sepconv1', 'block5_sepconv1_bn', 'block5_sepconv2_act', 'block5_sepconv2', 'block5_sepconv2_bn', 'block5_sepconv3_act', 'block5_sepconv3', 'block5_sepconv3_bn', 'add_4', 'block6_sepconv1_act', 'block6_sepconv1', 'block6_sepconv1_bn', 'block6_sepconv2_act', 'block6_sepconv2', 'block6_sepconv2_bn', 'block6_sepconv3_act', 'block6_sepconv3', 'block6_sepconv3_bn', 'add_5', 'block7_sepconv1_act', 'block7_sepconv1', 'block7_sepconv1_bn', 'block7_sepconv2_act', 'block7_sepconv2', 'block7_sepconv2_bn', 'block7_sepconv3_act', 'block7_sepconv3', 'block7_sepconv3_bn', 'add_6', 'block8_sepconv1_act', 'block8_sepconv1', 'block8_sepconv1_bn', 'block8_sepconv2_act', 'block8_sepconv2', 'block8_sepconv2_bn', 'block8_sepconv3_act', 'block8_sepconv3', 'block8_sepconv3_bn', 'add_7', 'block9_sepconv1_act', 'block9_sepconv1', 'block9_sepconv1_bn', 'block9_sepconv2_act', 'block9_sepconv2', 'block9_sepconv2_bn', 'block9_sepconv3_act', 'block9_sepconv3', 'block9_sepconv3_bn', 'add_8', 'block10_sepconv1_act', 'block10_sepconv1', 'block10_sepconv1_bn', 'block10_sepconv2_act', 'block10_sepconv2', 'block10_sepconv2_bn', 'block10_sepconv3_act', 'block10_sepconv3', 'block10_sepconv3_bn', 'add_9', 'block11_sepconv1_act', 'block11_sepconv1', 'block11_sepconv1_bn', 'block11_sepconv2_act', 'block11_sepconv2', 'block11_sepconv2_bn', 'block11_sepconv3_act', 'block11_sepconv3', 'block11_sepconv3_bn', 'add_10', 'block12_sepconv1_act', 'block12_sepconv1', 'block12_sepconv1_bn', 'block12_sepconv2_act', 'block12_sepconv2', 'block12_sepconv2_bn', 'block12_sepconv3_act', 'block12_sepconv3', 'block12_sepconv3_bn', 'add_11', 'block13_sepconv1_act', 'block13_sepconv1', 'block13_sepconv1_bn', 'block13_sepconv2_act', 'block13_sepconv2', 'block13_sepconv2_bn', 'conv2d_4', 'block13_pool', 'batch_normalization_4', 'add_12', 'block14_sepconv1', 'block14_sepconv1_bn', 'block14_sepconv1_act', 'block14_sepconv2', 'block14_sepconv2_bn', 'block14_sepconv2_act', 'avg_pool', 'dropout_1', 'input_1', 'predictions', 'loss_layer_2', 'input_2', 'loss_layer_1', 'external_reweighting_1', 'multiply_1'])
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f6b32fd88d0>>
Traceback (most recent call last):
`

**Comment by angeloskath** [comment]
Hi,

I am not able to reproduce your error. The following code works and will be added as a test case so that we do not have a regression in the future.

```python
#
# Copyright (c) 2017 Idiap Research Institute, http://www.idiap.ch/
# Written by Angelos Katharopoulos <angelos.katharopoulos@idiap.ch>
#

from functools import partial
import unittest

from keras.applications import Xception
from keras.datasets import cifar10
from keras.layers import Dense
from keras.models import Model
from keras.utils.np_utils import to_categorical
import numpy as np
from scipy.ndimage import zoom

from importance_sampling.training import ImportanceTraining


class TestFinetuning(unittest.TestCase):
    def _generate_images(self, x, y, batch_size=16):
        resize = partial(zoom, zoom=71.1/x.shape[1], order=3)
        while True:
            idxs = np.random.choice(len(x), batch_size)
            xi = np.stack([
                np.stack([
                    resize(c[:, :, 0])
                    for c in np.split(x[i], 3, axis=-1)
                ], axis=-1)
                for i in idxs
            ])
            yi = y[idxs]
            yield xi, yi

    def test_simple_cifar(self):
        (x_train, y_train), _ = cifar10.load_data()
        x_train = x_train.astype(np.float32) / 255.
        y_train = to_categorical(y_train)
        base = Xception(
            input_shape=(71, 71, 3),
            include_top=False,
            pooling="avg"
        )
        y = Dense(10, activation="softmax")(base.output)
        model = Model(base.input, y)
        model.compile("sgd", "categorical_crossentropy", metrics=["accuracy"])

        history = ImportanceTraining(model, presample=16).fit_generator(
            self._generate_images(x_train, y_train, batch_size=8),
            steps_per_epoch=10,
            epochs=1,
            batch_size=8
        )
        self.assertTrue("loss" in history.history)
        self.assertTrue("accuracy" in history.history)
        self.assertEqual(len(history.history["loss"]), 1)
        self.assertEqual(len(history.history["accuracy"]), 1)


if __name__ == "__main__":
    unittest.main()
```

If you still think there is a bug, could you please send a code snippet that reproduces the error?

I will close the bug tomorrow, but feel free to reopen it.

**Comment by theblackcat102** [comment]
I reloaded a new model and the sampling code is working. I will close the bug for now. Thanks
